### ISSUE TITLE
docker部署，多数请求报502错误，无法正常使用

### ISSUE THREAD

**Issue by XDwanj** [imsyy/SPlayer#252]
### 是网页端还是客户端

网页端

### 当前系统环境

Manjaro Linux

### 当前 Node.js 及 npm 版本

v18

### 当前版本

latest

## docker-compose yaml

```yaml
services:
  splayer:
    container_name: splayer
    image: imsyy/splayer:latest
    ports:
      - 3000:7899
    restart: unless-stopped
```
## docker 错误日志

[err.log](https://github.com/user-attachments/files/17005246/err.log)

## Firefox 浏览器 HAR 日志 （可拖入浏览器复现

[localhost_Archive [24-09-15 17-41-06].zip](https://github.com/user-attachments/files/17005321/localhost_Archive.24-09-15.17-41-06.zip)
